### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mavrick102** [Diazole/c4-dl#2]
i have tried pip install crypto, but all im getting is this still

C:\Users\maverick102\Desktop\c4-dl-master\c4-dl-master>py .\c4-dl.py --download --wvd "C:\widevine_device.wvd" --url "https://www.channel4.com/programmes/the-big-bang-theory/on-demand/44564-001"
Traceback (most recent call last):
File "C:\Users\maverick102\Desktop\c4-dl-master\c4-dl-master\c4-dl.py", line 12, in <module>
from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

can someone help please

**Comment by Diazole** [comment]
Read the readme.

```
pip install -r requirements.txt
```
